### ISSUE TITLE
Bug: Commit SHA is not supported by rekor index

### ISSUE THREAD

**Issue by asraa** [chainguard-dev/rekor-search-ui#19]
Hey!

Commit SHA is exposed in the search UI, and I assume this meant "find signatures signed at a particular commit SHA", but maybe it means "find sigs for a commit SHA signed with gitsign"? 

For e.g. I have a GH workflow signing at commit SHAs, e.g. rekor log index `2432260` as an example. It's commit SHA is `50e247ca7842e9cd709f9f21379d5ebbe3fbd779`, but the search UI does not find this.

Maybe add some clarification? I assume people may think that it means the former.

**Comment by pdeslaur** [comment]
You are correct - the UI is currenly only compatible with `gitsign`.  I think adding tooltip, or some other form of documentation in the UI would be useful!

Now I'm curious, do you happen to know what the hashed value corresponds to for `intoto` records? Is there another way we could search for the rekor entry you were trying to find?

**Comment by pdeslaur** [comment]
I've added documentation in the UI itself - feel free to reopen - or send other feedback as needed!
