### ISSUE TITLE
Configure Rekor instance

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/rekor-search-ui#31]
It could be cool to point the UI at other backends, eg the staging instance at https://rekor.sigstage.dev, or my own private rekor instance, without having to run a separate instance of the UI myself.

Since requests come from the browser, if I can personally reach the rekor instance, the UI should still work (right?).

**Comment by tuananh** [comment]
the requirement will then include the destination instance must have cors setup properly to allow the domain of this web app.

**Comment by imjasonh** [comment]
I believe the stock Rekor server already handles setting CORS headers. I hacked up the Rekor UI to point to https://rekor.sigstage.dev and it didn't seem to have any problem getting responses.

It's possible that a private Rekor instance could be configured not to allow CORS, or that it sits behind a proxy that strips CORS headers, but I think that's an issue of the Rekor instance, and not something the UI could do a lot about.

**Comment by di** [comment]
This would be really nice now that more people are running/testing against staging!

**Comment by pdeslaur** [comment]
Finally got to this - I'm aiming at getting the PR reviewed this week: #39 !
