### ISSUE TITLE
Display decoded `pyblicKey.content`

### ISSUE THREAD

**Issue by di** [chainguard-dev/rekor-search-ui#5]
In addition to just displaying the JSON that results from the Rekor entry, it'd be nice to be able to decode certain fields into something human-readable when present. Specifically, the `publicKey.content` field when it's a certificate.

**Comment by pdeslaur** [comment]
Alright - we have a demo version here: https://rekor-search-ui-git-fork-pdeslaur-x509.chainguard.app

We'll get that merged tomorrow.
